# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import os
import sys

from snakemake.utils import validate

# configfile: "config.yaml"
validate(config, "config.schema.yaml")


REF = os.path.abspath(config["reference"])
DSA = os.path.abspath(config["DSA"])
BAM = os.path.abspath(config["bam"])
VCF = config.get("vcf", [])
H1_TAG = config["h1-tag"]
H2_TAG = config["h2-tag"]

MAX_THREADS = config.get("max_threads", 64)
DEFAULT_ENV = "../envs/env.yml"

# get the name of the data from the bam
SM = [os.path.basename(BAM).split(".")[0]]


include: "rules/dsa-phase.smk"


# build the list of needed outputs
needed_outputs = expand(rules.cram.output.cram, sm=SM)
needed_outputs += expand(rules.add_assignments.output.cram, sm=SM)
if len(VCF) > 0:
    needed_outputs += expand(rules.haplotagged_vcf.output.vcf, sm=SM)


rule all:
    input:
        needed_outputs,
